### ISSUE TITLE
Add files as input & Add more than three inputs

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#12]
**Is your feature request related to a problem? Please describe.**

I can only add short inputs in the "Input or stdin" window. And I can only add three inputs.

**Describe the solution you'd like**

Support adding files as inputs. And support adding more than three inputs.

Maybe it's good to display the content of only three inputs, and others can be added by a popup window, or add from the webpage, which is described in #11.

**Describe alternatives you've considered**

Add a button "Run on file" which allows you to choose a file as the input.

**Additional context**

**Comment by coder3101** [comment]
I will add an option to maximize the input and output window in the next release. You will be also be able to choose the file you want to give as input but as for the 3 only inputs. It will stay the same. The danger will creating multiple runs at a time is that in some lower end machines, running your program on say 5-6 times at once could slow down the performance.

**Comment by coder3101** [comment]
In the last commit. An option to expand the input/ouput box was provided. When in Expanded mode you have ability to read input from any file. Hence fixed. The next release will be 3.0 that will include this feature.
