### ISSUE TITLE
Multiple Tabs support

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#13]
**Is your feature request related to a problem? Please describe.**

I can't edit multiple files in a single process (a single window), and I can't drag a file into the GUI in order to open it (the path will be added in the code insteadly).

Tabs in sublime text: 
![image](https://user-images.githubusercontent.com/30581822/70136794-a9b90780-16c7-11ea-85af-3eb90ec9c158.png)

Drag a file into CP Editor: 
![image](https://user-images.githubusercontent.com/30581822/70136833-b9d0e700-16c7-11ea-97c9-b1a04b0306e6.png)

**Describe the solution you'd like**

Add multiple tabs support, and I can drag a file into the GUI to open it.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
Adding as low priority. If you want to use/open multiple files at once, You could launch a new instance of editor. And cycle between them quickly with OS binding like `Win+Tab`. Adding Tabs is in my mind but not very likely in next few releases.

**Comment by coder3101** [comment]
About adding drag and drop to Application.

In mainwindow.cc, add following definition and also add the declaration in mainwindow.hpp

```cpp
MainWindow::MainWindow(QWidget *parent)
{
    ..........
    setAcceptDrops(true);
     .....
}

void MainWindow::dragEnterEvent(QDragEnterEvent *e)
{
    if (e->mimeData()->hasUrls()) {
        e->acceptProposedAction();
    }
}

void MainWindow::dropEvent(QDropEvent *e)
{
    for (const QUrl &url : e->mimeData()->urls()) {
        QString fileName = url.toLocalFile();
        qDebug() << "Dropped file:" << fileName;
    }
// Multiple files can be dropped, but editor can only open one file, so let it open file at index `0`. 
}
```

**Comment by coder3101** [comment]
Drag and drop has been implemented in the 3765283589510ecc9373cfe491fa29e1b7e3d78c

**Comment by coder3101** [comment]
Priority increasing due to high demand.

**Comment by coder3101** [comment]
This feature will be implemented on a new branch `multi-tab-support`. To be finally merged into `master` and released to public in `4.0`

**Comment by coder3101** [comment]
@ouuan I need you to test it extensively because it will involve a lot of UI and code changes and i do not want to break stuffs. As of now, the branch has code that can support multiple tab input, output and editor. Each Mainwindow has a index associated with it which will identify the Tab and temporary files and solutions and outputs are created as per the window index.

**Comment by coder3101** [comment]
Build the editor from `multi-tab-support branch`, it now has initial support of tabs, organized settings and resizeable editor and input/output.

**Comment by ouuan** [comment]
I think the minimum width should be no more than half of the resolution so that split-screen can work well.

**Comment by coder3101** [comment]
> I think the minimum width should be no more than half of the resolution so that split-screen can work well.

Okay, Some resizing needs to be done. Maybe you could try `mainwindows.ui` and set `minimumsizeHint` property of copiler_edit box and other boxes to smaller value and let me know which one you find is good. If you want to change this value for editor, you will find that in mainwindow.cc, inside `setUpEditor()` i set minimum values of size of editor.

These minimum values are threshold beyond which the widget cant be decreased.

Also, Saving and opening of new files in tabs are working nicely or not? I have not tested it

**Comment by coder3101** [comment]
Bringing Tabs, was surely a lot of code change. Literally every file needs to change, So i am not able to test things thoroughly. I need to make it ready before 1 January. This will eventually roll as new year `2020` update.

**Comment by ouuan** [comment]
I prefer only a single UI, codes and inputs/outputs change when the tab changes. I think that will make many things easier (for example, companion only affects the current tab / all splitters have the same width).

When opening an already opened file, no new tab should be created, it should be switched to the existing tab.

In the current version, if I drag a file into the text editor, the path will be added. I guess it's a QTextEdit feature, but not expected by most users. It should be the same as dragging a file into other places (to open this file).

**Comment by coder3101** [comment]
Some features that are, if you drag drop multiple files into editor, each is opened in separate tab.

**Comment by coder3101** [comment]
> I prefer only a single UI, codes and inputs/outputs change when the tab changes.
Yes it will change, there will be no effect of tabs, if you just use single tabs.

> When opening an already opened file, no new tab should be created, it should be switched to the existing tab.

I will look into it. Switching to tab if already opened. Nice feature

> In the current version, if I drag a file into the text editor, the path will be added.

I see a bug, It can be solved easily. i miss-typed something so this is happening

**Comment by ouuan** [comment]
> I prefer only a single UI, codes and inputs/outputs change when the tab changes.

By "multiple UI", I mean multiple `MainWindow`s.

**Comment by ouuan** [comment]
Or multiple these:

```cpp
  Ui::MainWindow *ui;
  QCodeEditor *editor;
  QString language;

  QString formatCommand, compileCommand, runCommand, prependCommand;
  QString templatePath;
  bool shouldSaveTests;

  Core::Formatter *formatter = nullptr;
  Core::IO::InputReader *inputReader = nullptr;
  Core::Compiler *compiler = nullptr;
  Core::Runner *runner = nullptr;
```

**Comment by coder3101** [comment]
> 
> 
> Or multiple these:
> 
> ```c++
>   Ui::MainWindow *ui;
>   QCodeEditor *editor;
>   QString language;
> 
>   QString formatCommand, compileCommand, runCommand, prependCommand;
>   QString templatePath;
>   bool shouldSaveTests;
> 
>   Core::Formatter *formatter = nullptr;
>   Core::IO::InputReader *inputReader = nullptr;
>   Core::Compiler *compiler = nullptr;
>   Core::Runner *runner = nullptr;
> ```

Yes, Every tab has a separate window and all these instances.

**Comment by ouuan** [comment]
But I think only a single one would be better.

**Comment by coder3101** [comment]
> 
> 
> But I think only a single one would be better.

It will not make any difference plus this way you have opportunity to use different language for each tab. Like suppose you want to solve some BigInt type problem you can use python instead of C++, in other tab. However if this is fixed or is one, this feature won't work. Also if one such tab crashed, the others would be unaffected because they have their own copy of resources.

Also you can drag the splitter all the way to one end and only one side will be maximized (other will be invisible, drag from side to make it visible). This can be used in Split mode, so you can make full editor only have code area, or full area with Boxes or keep splitter somewhere between for both visible at same time.

**Comment by coder3101** [comment]
![ ](https://i.imgur.com/zmnEO05.jpg)

You can drag from right to make boxes visible. You can use this in split mode

**Comment by ouuan** [comment]
I'd prefer dragging the splitter affects all tabs.

I think the language selection should be automatically done by filename suffix.

**Comment by coder3101** [comment]
> Remember the width of the splitter (the width of the most recently visited tab). Now new tabs have default splitter width.

This is working!

> I think the language selection should be automatically done by filename suffix. (Or there can be an option for each tab.)

User has always the ability to change the language for each tab. When files are drag-dropped or opened the language is picked from extensions. Everything except Preference Window is working.. You should test the things out and let me know any changes or bugs. Also, I have updated the settings keys! So compilers will report error for not being found on PATH. Reset preferences should work.

Also different language for different tabs are working nicely, you can confirm me on this!

**Comment by coder3101** [comment]
@ouuan Everything that people and you requested has been made into this branch `multi-tab -support`. Separate template for separate languages, quick language switch. Please try it and let me know anything else you want. I do not thing that, this release will fall tomorrow but later in the coming weeks. Regardless, it will be a 2020 update.

**Comment by coder3101** [comment]
@ouuan If you get time you can try and test the new editor from `multi-tab-support` branch. It is almost ready except for some settings. It has all new Settings and ability to set Keybindings, % editor themes like Monkai and Solarised.

**Comment by ouuan** [comment]
I think settings need refactoring, and using JSON to store settings may be a good choice.

**Comment by coder3101** [comment]
> I think settings need refactoring, and using JSON to store settings may be a good choice.

JSON? Any particular reason, the current settings is already portable and cross platform.

**Comment by ouuan** [comment]
> > I think settings need refactoring, and using JSON to store settings may be a good choice.
> 
> JSON? Any particular reason, the current settings is already portable and cross platform.

I mean QJsonValue.

**Comment by ouuan** [comment]
I mean the SettingsManager, not the local settings file.

**Comment by coder3101** [comment]
Yes I agree the current SettingsManager has lot of redundant code. So how does QjsonValue will make it better. I only want to make changes to manager and not the code that uses manager (backward compatible). How do you propose to do it?

**Comment by ouuan** [comment]
Wait, why not just use QSettings?

**Comment by ouuan** [comment]
Let me read the Qt docs first...

**Comment by ouuan** [comment]
Is it able to set some attributes in the UI, then update UI from settings and vice versa can be done by a loop?

**Comment by coder3101** [comment]
> Is it able to set some attributes in the UI, then update UI from settings and vice versa can be done by a loop?

Current preferencewindow.cpp file does exactly this. It applies and extracts attributes from UI to settings.

**Comment by ouuan** [comment]
In fact, I want to detect the change of settings in the preferences window. That will add codes for each setting again.

**Comment by ouuan** [comment]
https://doc.qt.io/qt-5/qobject.html#findChild

This seems helpful.

**Comment by ouuan** [comment]
Use https://doc.qt.io/qt-5/qsettings.html#childKeys and https://doc.qt.io/qt-5/qobject.html#findChild together, and use the same name for UI and settings, everything can be done in a loop.

**Comment by ouuan** [comment]
I'll open a new issue for it.

**Comment by ouuan** [comment]
I think this can be closed. Bugs / Feature Requests about multiple tabs should be discussed in new issues.

**Comment by coder3101** [comment]
I will look into it, but clearly you are more familiar with what you are requesting. Maybe if you get some time you could directly propose a PR rather an issue.

**Comment by ouuan** [comment]
OK, I'll try it tomorrow.

**Comment by ouuan** [comment]
Seems that the logic introduced in #44 is changed back again. I'll reimplement it.
