### ISSUE TITLE
Saved file is empty while the editor is running

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#14]
**Describe the bug**

After pressing the "Save" button, the file is empty until closing the editor.

**To Reproduce**

1. Open a file using the CP Editor.
2. Write something.
3. Press Ctrl+S.
4. View the file outside of the editor, it is empty.
5. Close the editor.
6. The codes are saved in the file.

**Expected behavior**

In the 4th step, the file shouldn't be empty.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/70137498-010ba780-16c9-11ea-9fea-0464852a8a94.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ouuan** [comment]
Also, the file is not saved when compiling.

**Comment by coder3101** [comment]
Fixed in 2.0.2

**Comment by ouuan** [comment]
This happens again in 2.0.3

(I don't know why, but I can't find the "Reopen" button.)

**Comment by coder3101** [comment]
Don't look into size. Right click and open the file in notepad. It should be saved. If not then tell me is it the save that is triggered after compilation or normal save.

**Comment by ouuan** [comment]
> Don't look into size. Right click and open the file in notepad. It should be saved. If not then tell me is it the save that is triggered after compilation or normal save.

Both compilation and normal save work well, but autosave doesn't.

**Comment by coder3101** [comment]
Point noted. I might have missed it while fixing other. A patch release today shall fix it.

**Comment by coder3101** [comment]
Hey @ouuan ,

Do you mind fixing this issue yourself and become a contributor. Here is what to do to fix the issue.

In the file named mainwindow.cpp, there will be a function named `onSaveTimerTriggered` (or something similar). Inside will be a line 

`openFile->write(...);`

add a new line after this : 

`openFile->flush();`

It will fix the issue, and send a PR with commit message "fixes #14".

**Comment by ouuan** [comment]
> Hey @ouuan ,
> 
> Do you mind fixing this issue yourself and become a contributor. Here is what to do to fix the issue.
> 
> In the file named mainwindow.cpp, there will be a function named `onSaveTimerTriggered` (or something similar). Inside will be a line
> 
> `openFile->write(...);`
> 
> add a new line after this :
> 
> `openFile->flush();`
> 
> It will fix the issue, and send a PR with commit message "fixes #14".

I'm not familiar with C++ projects with GUI, and I think I would make mistakes when trying to contribute. I'm not going to learn about this in the near future, so perhaps I can't be a contributor.

However, since you have told me how to fix this issue, I can open a PR to fix it.

**Comment by coder3101** [comment]
If your PR is merged you will become contributor.

**Comment by coder3101** [comment]
After Line 866, in file : src/mainwindow.cc add `openFile->flush();`

**Comment by ouuan** [comment]
> If your PR is merged you will become contributor.

Maybe I meant I couldn't be a collaborator.

**Comment by ouuan** [comment]
I'm installing Qt now for testing.

**Comment by coder3101** [comment]
There is no need to download and test it yourself unless if you have good Internet speed. But if you want to be very sure about it then as you wish.

**Comment by ouuan** [comment]
I just found that saving when opening a new session also has a bug. So I want to test it.

**Comment by coder3101** [comment]
Adding that line should fix the issue, the changes to file are buffered and not committed unless flushed. Like interactive problem in CF, flushing makes sure that changes have been written back to file.

**Comment by ouuan** [comment]
OK, I will open a PR then.
