### ISSUE TITLE
Use Competitive Companion to parse tasks

### ISSUE THREAD

**Issue by Salil03** [coder3101/cp-editor2#15]
**Is your feature request related to a problem? Please describe.**
This editor will be a complete package if it can parse test data from online judges. Currently it takes some time to create a new folder, load the template, etc.

**Describe the solution you'd like**
 You can use [Competitive Companion](https://github.com/jmerle/competitive-companion) to parse the test data. See this vscode extension [ACMX](https://github.com/mfornet/acmx) as a demo. It creates a new folder and new file after parsing the data from online judges.

**Describe alternatives you've considered**
You can use other tools like https://github.com/xalanq/cf-tool. In my opinion the above solution is better because Competitive Companion supports a lot of online judges and not only codeforces.

**Additional context**

**Comment by coder3101** [comment]
I have used and liked ACMX but it was sometimes slow and it doesn't work on Windows Natively. Needs WSL. Competitive Companion is good and works nicely.

**Comment by coder3101** [comment]
Added in CP Editor 3.0

**Comment by ouuan** [comment]
@allcontributors add @Salil03 as a contributor for ideas.

**Comment by Salil03** [comment]
Thanks @ouuan :)
