### ISSUE TITLE
Expand editor's size

### ISSUE THREAD

**Issue by Arthur-QQ** [coder3101/cp-editor2#16]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
When a code line is very long, a sliding bar appears at the bottom of the editor. It allows us to see the whole line ( see https://i.imgur.com/jNnrBNc.png ). But I feel like there should be an option for scaling the part of the editor in which we type ( I'm talking about this horizontal double arrow https://i.imgur.com/9Kh1gKp.gifv ). With this enhancement, the user would not spend too much time pressing the arrow keys nor scrolling the bottom bar during a contest (in order to edit or see the right part of a given line of code). The contestant would be able to simply click at the part of the code he/she wants to go to.

Furthermore, it is also a feature that puts CP Editor's quality closer to VS Code's, Atom's, etc..

**Describe alternatives you've considered**
Using the scrolling bar or pressing arrow keys which is considerably slower.

**Additional context**
N/A

**Comment by coder3101** [comment]
For the time being you can turn Word Wrap on. It will Wrap text and you can navigate in a better way.

**Comment by coder3101** [comment]
Also, There is a general thumb of rule that says, your code should be only 80-100 character long per line. 

If you use a formatter, like clang. It will format your code in a way that you will not need to scroll.

**Comment by coder3101** [comment]
Closing this issue as word wrap mitigates this behavior. The current editor size is standard size of popular editor like `neovim`.
