### ISSUE TITLE
Add function parameter hints

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#18]
**Is your feature request related to a problem? Please describe.**

Parameter hints are very helpful, especially when writing some advanced data structures, or use unfamiliar STL functions.

**Describe the solution you'd like**

Something like this:

![image](https://user-images.githubusercontent.com/30581822/70290383-b138f780-1812-11ea-9003-2cfe74a4f57b.png)

**Describe alternatives you've considered**

N/A

**Additional context**

It seems hard to implement this function, so it can be considered with low priority.

**Comment by coder3101** [comment]
Such behavior requires an Language Server. Maybe if it could be done by parsing but you should transfer this issue to the editor.

**Comment by coder3101** [comment]
Reopen it here : https://github.com/Megaxela/QCodeEditor
