### ISSUE TITLE
Tabs are replaced by spaces

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#19]
**Describe the bug**

All tabs are replaced by spaces, so that I need to delete 4 characters in order to delete an indent.

**To Reproduce**

1. Press Tab.
2. Press Backspace, you need to press it four times in order to delete the indent.

**Expected behavior**

Tabs won't be replaced by spaces, and I need only one Backspace to delete it.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0

**Smartphone (please complete the following information):**

N/A

**Additional context**

There can be a setting of whether Tabs will be replaced by spaces.

I know I can use Shift+Tab, but I'm used to using Backspace for single Tab deletion.

**Comment by coder3101** [comment]
Good Issue. Will be fixed in next Patch Update.

**Comment by coder3101** [comment]
Fixed in 2.0.2

**Comment by coder3101** [comment]
The auto indent will always use `Spaces`. Anything you type manually `Tabs` will be preserved.

**Comment by ouuan** [comment]
There should be an option for tab length.

**Comment by ouuan** [comment]
And auto-indentation is not available for tabs is really annoying. In this version, I'd rather disable the "Use Tabs" option.

**Comment by coder3101** [comment]
Again I must assert that the code editor widget is a `third_party/QCodeEditor`, which is not maintained by me rather is a Dependency. If you want to add that feature. Go to his repository and open an Issue, as soon as he fixes it, I will update dependency and it will be done.

**Comment by coder3101** [comment]
Here is the dependency https://github.com/Megaxela/QCodeEditor

It is well maintained and will be fixed.

**Comment by ouuan** [comment]
It seems that QCodeEditor has "Replace tabs with spaces" as an option:

![image](https://user-images.githubusercontent.com/30581822/70328872-09a0e100-1875-11ea-8ac2-0d138b05a9bb.png)

**Comment by coder3101** [comment]
My current editor does the exact same things. When you click Use tab, it enables that same flag. But i know why it is happening, I will open a PR on his repository and when he merges it, I will update the same on my editor.

**Comment by ouuan** [comment]
> There should be an option for tab length.

And don't forget this.

**Comment by coder3101** [comment]
Sure thing. Maybe you could open another issue here like "Auto indent always uses spaces" and another with issue like "Auto-parentheses`{` on this always adds a new line and `}`".

In some cases like vec.push_back({2,3}); you will get a new line and indentation as soon as you type `{` making it look bad.

**Comment by coder3101** [comment]
Fixed and added option to set Tab Size, in last commit

**Comment by coder3101** [comment]
Hey @ouuan ,
In the coming release this will b fixed completely. It has been already updated in `master` and here is th PR of the same. It was indeed an Editor Issue. See https://github.com/Megaxela/QCodeEditor/pull/19
