### ISSUE TITLE
Showing compiler warnings

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#20]
**Is your feature request related to a problem? Please describe.**

I can't see the compiler warnings.

**Describe the solution you'd like**

Show compiler warnings after compiling.

Maybe add a setting of whether to show the warnings or not. (However, this can be done by adding `-w` in the compile command.)

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
Fixed in the last release. Version 2.0.2

**Comment by ouuan** [comment]
Now it shows 
![image](https://user-images.githubusercontent.com/30581822/70324617-f2f58c80-186a-11ea-9b7c-f4591e6bbcc8.png)
 when there aren't any warnings.

**Comment by coder3101** [comment]
It's empty. Means no warning. I will remove it in next release. So it won't show any warning if there is no.

**Comment by coder3101** [comment]
By the time ignore this message.

**Comment by coder3101** [comment]
Fixed in last commits.
