### ISSUE TITLE
Memorize the size of the window

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#22]
**Is your feature request related to a problem? Please describe.**

Every time I open the CP Editor, its size is the same, even I changed its size last time.

**Describe the solution you'd like**

When I open the editor, its size should be the same as I closed it last time.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by coder3101** [comment]
By size you mean. Windows Size? I can make it open maximized by default. Will that be Okay?

**Comment by ouuan** [comment]
> By size you mean. Windows Size? I can make it open maximized by default. Will that be Okay?

It's okay for me, because I usually use full window. But I think memorizing the size of the last use would be good for everyone. Many other editors/IDEs have this function.

**Comment by coder3101** [comment]
In a few minute a release will be up, Which fixes this issue. If it doesn't fixes the issue you can re-open this issue.

**Comment by ouuan** [comment]
Full size and not full size should be treated separately:

1. Open the editor, now it's not full size, but with size x.
2. Click "full size" button, now it's full size.
3. Close the editor.
4. Open the editor, the editor should be full size.
5. Click "restore" button, now it's not full size, but with size x (which is mentioned in step 1).
6. Change the size to y.
7. Close the editor.
8. Open the editor, the size should be y.

In the version 2.0.2, if you turn to full size in the last session, next time it will be not full size, but the size is big so that it looks like it's full size.

(I'm not so sure about the English expression of "not full size" and "restore", also there may be some grammar mistakes, hope you can understand.)

**Comment by coder3101** [comment]
The editor opens in Full screen but not Maximised. I am aware of this but this does the work done for a hot fix. In some other future release the issue of Maximised and Full screen will be solved.

**Comment by coder3101** [comment]
Fixed in last commits.
