### ISSUE TITLE
Save when compiling / closing warning only when the file is not saved

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#23]
**Is your feature request related to a problem? Please describe.**

I usually forget to save the file, because I'm used to other IDEs which automatically save files when compiling, and warn you at closing only when the file is not saved.

**Describe the solution you'd like**

I think the file should be saved when compiling, or make it an option. Maybe only be enabled when the corresponding file is specified, which allows compiling without the file like the online IDEs.

Also, I think the warning when closing the editor should only be there when the file is not saved.

Something represents for "the file has been modified" is also helpful, like:

![image](https://user-images.githubusercontent.com/30581822/70326387-6c8f7980-186f-11ea-9727-0f1ae0a9accd.png)

![image](https://user-images.githubusercontent.com/30581822/70326372-66010200-186f-11ea-96b2-e32c37653c90.png)

**Describe alternatives you've considered**

Different warnings for normal exiting / exiting without saving.

**Additional context**

N/A

**Comment by coder3101** [comment]
When you start a new session the app automatically saves the current buffer.

**Comment by coder3101** [comment]
Fixed. Now Editor saves the buffer each time compilation is requested.

**Comment by ouuan** [comment]
> Also, I think the warning when closing the editor should only be there when the file is not saved.
>
> Something represents for "the file has been modified" is also helpful, like:
>
> ![image](https://user-images.githubusercontent.com/30581822/70326387-6c8f7980-186f-11ea-9727-0f1ae0a9accd.png)
>
> ![image](https://user-images.githubusercontent.com/30581822/70326372-66010200-186f-11ea-96b2-e32c37653c90.png)

This part is not fixed yet.
