### ISSUE TITLE
cmd window flashes when opening and update settings

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#24]
**Describe the bug**

The cmd window flashes every time when I open the editor and update the settings.

**To Reproduce**

It happens every time.

**Expected behavior**

There shouldn't be such windows, or they shouldn't be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/30581822/70327796-8c746c80-1872-11ea-9d85-46387f449722.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1903 18362.476
 - Version: 2.0.2

**Smartphone (please complete the following information):**

N/A

**Additional context**

It only happens on my laptop, not on another desktop PC.

**Comment by coder3101** [comment]
Those flashing CMD checks if compile, Run command are okay or not. I will add another way to check for them and this issue will be gone.

**Comment by coder3101** [comment]
Fixed in last commit.
