### ISSUE TITLE
Save the inputs and outputs in the file

### ISSUE THREAD

**Issue by ouuan** [coder3101/cp-editor2#25]
**Is your feature request related to a problem? Please describe.**

I need to re-enter the inputs and outputs when I open a file again.

**Describe the solution you'd like**

Save the corresponding relationship between the file path and the inputs and outputs in CP Editor, when opening files with the same path, the inputs and outputs are the same.

**Describe alternatives you've considered**

Save the inputs and outputs in the file, for example, save them in the annotations with JSON.

**Additional context**

It's from [this comment](https://codeforces.com/blog/entry/71907?#comment-562683) .

**Comment by coder3101** [comment]
As great as it sounds, The only way to achieve this is for editor to have it's own file like (.cpe), these files will bundle the source and it's inputs together. This will also make those files exclusive and will be opened only by cpeditor. 

The method that you have specified that says remembering the input and program file relation. Will not be viable as per the design. 

However, In coming release i will add an option that will allow you to read to inputbox from input.txt for some file. You can manually generate the input file and then open it to input box.

**Comment by coder3101** [comment]
Fixed Partially with #12 
(Now you can manually create a input file and use Expanded window to read it to editor)
