### ISSUE TITLE
Bracket removal

### ISSUE THREAD

**Issue by testitem** [coder3101/cp-editor2#42]
**Is your feature request related to a problem? Please describe.**
Whenever you delete an opening bracket or parentheses as a typo, it won't delete the corresponding closing bracket.

**Describe the solution you'd like**
Let's say the cursor is at the `I`.  
In `a(I)b` and `a()Ib`, when you press Backspace, it should become `ab`. but in `a(Ibcd)e` when you press Backspace it should still be `aIbcd)e`.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by coder3101** [comment]
Hey, 
Thanks for your feedback!

This editor is a third party dependency, the issue status can be tracked here. https://github.com/Megaxela/QCodeEditor/issues/23

Once, it is fixed it will get fixed there, it will be fixed in this repository as well.
