### ISSUE TITLE
AppImage is not working

### ISSUE THREAD

**Issue by ahmfuad** [coder3101/cp-editor2#5]
**Describe the bug**
I'm currently using Manjaro Linux. The AppImage file is not working on this OS. After making the Appimage executable and running it nothing happens. 

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux]
 - Version [18.0.4]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by coder3101** [comment]
In future release this issue will be fixed. Moreover in coming release I plan to add this editor to AUR. So you can download it as native app with icon and all. As for AppImage it is because of newer glibc that is used during package in my Arch Linux

**Comment by coder3101** [comment]
If the newer release AppImage Runs then please close this issue for me to know.

**Comment by ouuan** [comment]
@allcontributors add @ahmfuad as a contributor for bug report.
