### ISSUE TITLE
WA when output is exactly as expected

### ISSUE THREAD

**Issue by DT3264** [coder3101/cp-editor2#55]
**Describe the bug**
Veredict is WA when output is exaclty as expected

**To Reproduce**
1. Fetch this problem [https://codeforces.com/contest/1281/problem/C](1281C)
2. Insert this solution 

> #include<bits/stdc++.h>
using namespace std;
long long mod = 1000000007;
int main(){
    ios::sync_with_stdio(false);
    cin.tie(0);
    long long i, j;
    long long n;
    long long x;
    string s;
    cin >> n;
    while(n--){
        s="";
        cin >> x >> s;
        int pos=0;
        long long actLen=s.length();
        while(s.length() < x){
            string tempS = s.substr(pos+1, string::npos);
            for(i='0'; i<s[pos]-1; i++){
                for(j=0; j<tempS.length() && s.length() < x; j++){
                    s+=tempS[j];
                }
            }
            pos++;
        }
        long long ans;
        for(i=0; i<x; i++){
            long long mult = s[i]-'0';
            actLen = (i+1)+(((actLen-(i+1))%mod)*(mult%mod));
            //cout << actLen<< "\n";
        }
        cout << actLen%mod << "\n";
    }
}

3. Compile and Run
4. Veredict is WA

**Screenshots**
![Anotación 2019-12-16 080718](https://user-images.githubusercontent.com/45462106/70913170-1a6ef680-1fdb-11ea-8b9f-1d2547b72c22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10x64bits

**Comment by ouuan** [comment]
It's already fixed in #43, please wait for the new release.

**Comment by coder3101** [comment]
Fixed, Please update to 3.1.0
