### ISSUE TITLE
Highlight multiple lines to indent/unindent

### ISSUE THREAD

**Issue by ahzong** [coder3101/cp-editor2#57]
**Is your feature request related to a problem? Please describe.**
It's not convenient when I want to indent/unindent multiple lines together.

**Describe the solution you'd like**
I can highlight the lines I want to indent/unindent, then press Tab/Shift+Tab to indent/unindent all the highlighted lines at the same time.

**Describe alternatives you've considered**
Other hotkeys are also preferred.

**Additional context**
N/A

**Comment by coder3101** [comment]
This is already opened in its place. See https://github.com/Megaxela/QCodeEditor/issues/18
