### ISSUE TITLE
Program crashes when trying to save/open file (Windows)

### ISSUE THREAD

**Issue by Arthur-QQ** [coder3101/cp-editor2#6]
**Describe the bug**
I've been having trouble to save files. When I press Ctrl+S or go to "file -> save", the file explorer window pops up. The problem is that 1~2 seconds after it pops out, not just the file explorer window stops working, but also does the entire code editor. The same thing happens when I try to open a file or do anything that involves opening a file explorer window. This problem isn't being experienced only by me: this CodeForces user also complains of it https://codeforces.com/blog/entry/71673?#comment-56041 .

**Expected behavior**
The program was not supposed to crash

**To Reproduce**
1. Go to 'File'
2. Click on 'Save' / Skip step 1 and press Ctrl+S
3. See error

**Screenshots**
https://i.imgur.com/PYPI6FR.gifv

**Desktop (please complete the following information):**
 -OS: Windows 8.1 (version 6.3.9600 / 64 bits)

**Smartphone (please complete the following information):**

**Additional context**
I downloaded the "stable 1.50.2" release from https://github.com/coder3101/cp-editor2/releases .

**Comment by coder3101** [comment]
Strange. It works nicely on my Windows 10. I will look into it maybe some nullptr exception. Or some incompatibility with Qt version.

**Comment by coder3101** [comment]
This issue requires confirmation. I do not have this issue with my Windows 10 and in Linux, nor is this Issue pointed out by any other User. If anyone else finds this issue, please comment here to let me know.
