### ISSUE TITLE
Support for more themes - Monokai

### ISSUE THREAD

**Issue by sum-mer-park** [coder3101/cp-editor2#60]
Add in support for more themes like the one in sublime text 3.

The current theme looks like Xcode. It's not bad, but it's kind of bluish.

Some themes which i would recommend is Monokai , Brogrammer etc

**Comment by coder3101** [comment]
Hey, I have added themes like "Monkai (Sublime theme), Solarised light and Solarised dark". Hope that solves this issue. The update 4.0 will release this whole new Editor with more themes, more tabs and whole new design.

**Comment by ouuan** [comment]
@allcontributors add @s6059r as a contributor for ideas.
