### ISSUE TITLE
Some new feature suggestion

### ISSUE THREAD

**Issue by Exile-2k4** [coder3101/cp-editor2#61]
I think you should add some feature below, which is common on many IDEs we are using now:
 
- ~Multiple line comment/uncomment/tab (important, many IDEs have this)~ See : https://github.com/Megaxela/QCodeEditor/issues/27 and https://github.com/Megaxela/QCodeEditor/issues/18
- Multiple-file access.
- Preset and save the compiler parameter for all language (like C++, Java, Python,...) so we won't have to change it when we switch programming language.
- ~More themes (Monokai, Atom, etc) whatever you can add, or even better, you can add Custom Theme feature.~. See #60 
- Indentation Coloring (wonderful for Python programmer)
- ~An option to set the time limit for a problem, and show up the  #execution time.~. On Linux your program must terminate after 5 sec of start and on windows there is no such limit. However, I have added now, the execution time is also showed. 
- ~Detached Execution should do the trick even if we don't have system("pause") command.~. This works on Linux! xterm pauses after execution however on Windows due to CMD limitations, it is not possible now! If we migrate to Powershell, this will be fixed, but due to backward compatibility we still detach on `CMD.exe`.

**Comment by coder3101** [comment]
>     * Indentation Coloring (wonderful for Python programmer)

Please open this issue at https://github.com/Megaxela/QCodeEditor

**Comment by coder3101** [comment]
>     * Preset and save the compiler parameter for all language (like C++, Java, Python,...) so we won't have to change it when we switch programming language.

Please Open this as Separate Issue by following the template. I didn't added this feature because, I thought that Changing language is not very frequent and is usually not done on daily basis. But I may consider this, @ouuan your views please!

**Comment by coder3101** [comment]
> Multiple-file access.

If you mean multiple tabs to open multiple file. This is already reported here #13

**Comment by coder3101** [comment]
Closing this issue as mostly things are reported. @Exile-2k4 you may need to open a new issue for Presets. Please also follow the template.

**Comment by ouuan** [comment]
@Exile-2k4 Detached run with pause on WIndows is available now.

https://github.com/coder3101/cp-editor/commit/c96643119cc70e80a7bec96c34d289514a4c366e#diff-1069ab23e05ddf7d96ad44ea2877dd9fR100

https://stackoverflow.com/questions/53453368/pass-a-pause-command-to-a-start-command-in-a-batch-file

**Comment by ouuan** [comment]
@allcontributors add @Exile-2k4 as a contributor for ideas.
