### ISSUE TITLE
Regarding Indentation 

### ISSUE THREAD

**Issue by Brijesh1in** [coder3101/cp-editor2#63]
**Is your feature request related to a problem? Please describe.**
Whenever I am using the for loop or anything like that and not using the parenthesis then it just goes to the new line .
Like : for( int i = 0 ; i < 10 ; ++i)
         *the pointer comes here .

**Describe the solution you'd like**
If the pointer comes here that would be nice idea .
Like : for( int i = 0 ; i < 10 ; ++i)
             *if the pointer comes here that would be nice .

It would be amazing if you add this feature for automatic parenthesis like let's say we are writing some code inside an if Like this .
         if( i==10)
              update something .

But let's say we missed something and I want to add a new line below the update something then I must use parenthesis 
        if(i==10)
             update something .
             again doing something .
Now I need to put bracket on the both ends when in the beginning and in the end 
        if(i==10){
             update something .
             again doing something .
        }

Now it will be amazing if I add only the beginning bracket and the end bracket automatic comes at the right place .

**Comment by ouuan** [comment]
You mean: select some texts & press `{` → "{\<selection\>}"?

**Comment by coder3101** [comment]
Seems like an Editor Issue. Forwarding to Megaxela

**Comment by coder3101** [comment]
You can check your issue here https://github.com/Megaxela/QCodeEditor/issues/29
