### ISSUE TITLE
Request for the suggestions

### ISSUE THREAD

**Issue by Brijesh1in** [coder3101/cp-editor2#64]
**Is your feature request related to a problem? Please describe.**
It is not suggesting whatever variables I have used .

**Describe the solution you'd like**
I want the editor to suggest those words that I have used only in writing code not anything extra (like language suggestion for let's say I am including something then I don't want suggestions ).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by coder3101** [comment]
You mean suggestion like Geany Editor

**Comment by Brijesh1in** [comment]
I don't know about geany but something like sublime text . But sublime suggest you inbuilt things and I just want my used words . So after removing system suggestion from sublime .

**Comment by coder3101** [comment]
Work in Progress at See https://github.com/Megaxela/QCodeEditor/issues/21
