### ISSUE TITLE
Key-Triggered templates

### ISSUE THREAD

**Issue by samael042** [coder3101/cp-editor2#66]
**Is your feature request related to a problem? Please describe.**
It's kinda annoying to copy and paste your template every time you create a new file.

**Describe the solution you'd like**
A template/snippet which is key triggered.  

**Describe alternatives you've considered**
If a Key Triggered template is not an option, a default template maybe(gets triggered by the click of a button)? This eliminates the possibility of being able to use multiple templates.

**Additional context**

**Comment by ouuan** [comment]
You can choose a default template in the current version:

![image](https://user-images.githubusercontent.com/30581822/71610721-65d5f700-2bce-11ea-9c3e-9fd3e6195614.png)

**Comment by coder3101** [comment]
I don't get it. what template are you talking about? You have the ability to choose a template file and everytime you open the editor. the contents of template file specified will be made available to you. Have you tried Setting a template file?

**Comment by samael042** [comment]
I meant something like [this](https://www.granneman.com/webdev/editors/sublime-text/top-features-of-sublime-text/quickly-insert-text-and-code-with-sublime-text-snippets).
I know the default template option is very useful, but if I want to use a DS, instead of opening my github and copying it I can use a keyword triggered code snippet instead.

**Comment by coder3101** [comment]
This is exactly the request that will come up with snippets support. You will have ability to add snippets of code (could be DS) and then with hotkey for snippets you will be able to choose and quickly paste any snippets in the editor. See this #56
