### ISSUE TITLE
Open .cpp file with CP editor

### ISSUE THREAD

**Issue by Arthur-QQ** [coder3101/cp-editor2#7]
**Is your feature request related to a problem? Please describe.**
If this feature was added, there would be a solution to the issue regarding the crash of the editor when it opens the file explorer. This bug doesn't allow some users to save/open files directly from the program and is completely explained here: https://github.com/coder3101/cp-editor2/issues/6 .

**Describe the solution you'd like**
When I select and right-click a .cpp file in the file explorer, there's no "Open with CP editor" option. Moreover, when I force the editor to open a .cpp file, it opens as if I opened it by double-clicking the executable file.

Furthermore, this feature exists in nearly every code editor. Therefore adding it would not only improve the program's quality but also benefit users who don't experience the bug.

**Describe alternatives you've considered**
N/A
**Additional context**
Here's a gif of what I've been trying to do: https://i.imgur.com/swpWIcB.gifv

**Comment by coder3101** [comment]
Thanks for your time and explaining me the issue. I will add this feature soon

**Comment by coder3101** [comment]
This feature should be working in latest release. Download it and check, if it works please close this issue for me to know. Check Codeforces blog for changes

**Comment by ouuan** [comment]
@allcontributors add @Arthur-QQ as a contributor for ideas and bug report.
