### ISSUE TITLE
No output from stderr

### ISSUE THREAD

**Issue by fedimser** [coder3101/cp-editor2#8]
**Describe the bug**
No output from stderr when asserton failed.

**To Reproduce**
1. Write C++ program which writes to stderr and the fails assertion;
2. Enter anything in "Input or stdin" textbox;
3. Click "Compile and run".
4. Only message "[Non-zero exit code 3]" appears in "Compiler Messages and stderr".

**Expected behavior**
Message written into stderr and message abut failing assertion seen in "Compiler Messages and stderr".

**Screenshots**
![image](https://user-images.githubusercontent.com/14271071/69907324-3794aa00-13cb-11ea-8d3e-7f308a9869aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
See assertion on which line has failed is very useful for debugging.

**Comment by coder3101** [comment]
This feature will be made available in CP Editor 2.0 that is about to be released today. (In next 24 hours). Keep checking Codeforces blog. You can close this issue yourself if you find the update fixes it

**Comment by coder3101** [comment]
This feature has been added in CP Editor 2.0. Please check it and if it works close this issue.

**Comment by coder3101** [comment]
Fixed in CP Editor 2.0

Reopen if you believe it is not fixed.

Thanks

**Comment by ouuan** [comment]
@allcontributors add @fedimser as a contributor for bug report.
