### ISSUE TITLE
Input/ ouput fields not getting cleared on New Session

### ISSUE THREAD

**Issue by CodingNinja1706** [coder3101/cp-editor2#9]
**Describe the bug**
When we are creating a new session then the input and output fields are not getting cleared.

**To Reproduce**
N/A

**Expected behavior**
Input and output fields should get empty on creating a new session

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Samsung j4+
 - OS: Android 9
 - Browser Chrome

**Additional context**
-

**Comment by coder3101** [comment]
This issue is welcome for contributing.

**Comment by ouuan** [comment]
@allcontributors add as a contributor for code and bug report.

**Comment by ouuan** [comment]
@allcontributors add @yatharth1706 as a contributor for code and bug report.
